package net

import (
	"crypto/tls"
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"net/http"
	"strings"
)

type Query struct {
	Header *http.Header
	Cache  *Cache
}

func NewQuery() *Query {

}

// QueryGet ...
func QueryGet(url string) (*goquery.Document, error) {
	if cli == nil {
		cli = http.DefaultClient
	}

	res, err := cli.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()
	if res.StatusCode != 200 {
		return nil, fmt.Errorf("status code error: %d %s", res.StatusCode, res.Status)
	}

	doc, err := goquery.NewDocumentFromReader(res.Body)
	return doc, err
}

func CacheQuery(url string) (*goquery.Document, error) {
	reader, e := cache.Reader(url)
	if e != nil {
		return nil, e
	}
	//if cli == nil {
	//	cli = http.DefaultClient
	//}
	//
	//res, err := cli.Get(url)
	//if err != nil {
	//	log.Fatal(err)
	//}
	//defer res.Body.Close()
	//if res.StatusCode != 200 {
	//	return nil, fmt.Errorf("status code error: %d %s", res.StatusCode, res.Status)
	//}

	doc, err := goquery.NewDocumentFromReader(reader)
	return doc, err
}
func HanChengHeader(wd string) {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// TODO: This is insecure; use only in dev environments.
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: tr}

	body := strings.NewReader(`wd=^%^E4^%^BA^%^85`)
	req, err := http.NewRequest("POST", "http://hy.httpcn.com/bushou/zi/", body)
	if err != nil {
		// handle err
	}
	req.Header.Set("Cookie", "UM_distinctid=16c2efb5e9e134-0cfc801ee6ae06-353166-1fa400-16c2efb5e9f3c8; Hm_lvt_cd7ed86134e0e3138a7cf1994e6966c8=1564156322,1565017408; CNZZDATA1267010321=1299014713-1564151968-^%^7C1565183518; hy_so_1=^%^255B^%^257B^%^2522zi^%^2522^%^253A^%^2522^%^25E6^%^259D^%^258E^%^2522^%^252C^%^2522url^%^2522^%^253A^%^252227^%^252FPWTBILILTBTBMEILE^%^252F^%^2522^%^252C^%^2522py^%^2522^%^253A^%^2522l^%^25C7^%^2590^%^252C^%^2522^%^252C^%^2522bushou^%^2522^%^253A^%^2522^%^25E6^%^259C^%^25A8^%^2522^%^252C^%^2522num^%^2522^%^253A^%^25227^%^2522^%^257D^%^255D; hy_so_4=^%^255B^%^257B^%^2522zi^%^2522^%^253A^%^2522^%^25E8^%^2592^%^258B^%^2522^%^252C^%^2522url^%^2522^%^253A^%^252234^%^252FKOKORNKOCQXVILXVB^%^252F^%^2522^%^252C^%^2522py^%^2522^%^253A^%^2522ji^%^25C7^%^258Eng^%^252C^%^2522^%^252C^%^2522bushou^%^2522^%^253A^%^2522^%^25E8^%^2589^%^25B9^%^2522^%^252C^%^2522num^%^2522^%^253A^%^252217^%^2522^%^257D^%^252C^%^257B^%^2522zi^%^2522^%^253A^%^2522^%^25E6^%^259D^%^258E^%^2522^%^252C^%^2522url^%^2522^%^253A^%^252227^%^252FPWTBILILTBTBMEILE^%^252F^%^2522^%^252C^%^2522py^%^2522^%^253A^%^2522l^%^25C7^%^2590^%^252C^%^2522^%^252C^%^2522bushou^%^2522^%^253A^%^2522^%^25E6^%^259C^%^25A8^%^2522^%^252C^%^2522num^%^2522^%^253A^%^25227^%^2522^%^257D^%^255D; ASP.NET_SessionId=lceymsersbrsquifblfr2ewm")
	req.Header.Set("Origin", "http://hy.httpcn.com")
	req.Header.Set("Accept-Encoding", "gzip, deflate")
	req.Header.Set("Accept-Language", "zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q=0.6")
	req.Header.Set("User-Agent", "Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1")
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Referer", "http://hy.httpcn.com/bushou/zi/")
	req.Header.Set("X-Requested-With", "XMLHttpRequest")
	req.Header.Set("Connection", "keep-alive")

	resp, err := client.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()

}
